name: code_de_la_route
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.0+4

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  video_player: ^2.8.6
  dot_navigation_bar: ^1.0.2
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1
  equatable: ^2.0.5
  provider: ^6.1.2
  url_launcher: ^6.2.6
  share_plus: ^9.0.0
  ionicons: ^0.2.2
  lottie: ^3.1.0
  audioplayers: ^6.0.0
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    # 
    - assets/audio/
    # 
    - assets/images/
    - assets/images/categories/
    - assets/images/degagement/
    - assets/images/signalisation/
    # 
    - assets/fonts/
    # 
    - assets/video/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
          style: normal
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 900
        - asset: assets/fonts/ProductSans-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/ProductSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/ProductSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/ProductSans-BlackItalic.ttf
          style: italic
          weight: 900