name: codedelaroute
version: 2.4.1+6
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6

  video_player: ^2.8.6
  dot_navigation_bar: ^1.0.2
  # equatable: ^2.0.5
  url_launcher: ^6.2.6
  share_plus: ^9.0.0
  ionicons: ^0.2.2
  lottie: ^3.1.0
  audioplayers: ^6.0.0
  # glassmorphism: ^3.0.0
  package_info_plus: ^8.0.0
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  google_sign_in: ^6.2.1
  flutter: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  top_snackbar_flutter: ^3.1.0

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    # 
    - assets/audio/
    # 
    - assets/images/
    - assets/images/categories/
    - assets/images/degagement/
    - assets/images/signalisation/
    # 
    - assets/fonts/
    # 
    - assets/video/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
          style: normal
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 900
        - asset: assets/fonts/ProductSans-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/ProductSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/ProductSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/ProductSans-BlackItalic.ttf
          style: italic
          weight: 900


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"
